CREATE DATABASE IF NOT EXISTS bdcfp;
USE bdcfp;
CREATE TABLE IF NOT EXISTS E01_TELEFONO (
codigo_area INT(3) NOT NULL,
nro_telefono INT(7) NOT NULL,
tipo CHAR(1)
)
CONSTRAINT FOREIGN KEY (nro_cliente) REFERENCES E01_CLIENTE (nro_cliente)]
